baseURL = "https://datapio.co/"
languageCode = "en-us"
title = "Datapio"
staticDir = ["static"]

[params]

dateFormat = "Monday, January 2, 2006"
github = "https://github.com/datapio/"
talkyardServerUrl = "https://comments-for-datapio-co.talkyard.net"
talkyardScriptUrl = "https://c1.ty-cdn.net/-/talkyard-comments.min.js"

[[params.menu]]

uri = "/news"

[[params.menu]]

uri = "https://comments-for-datapio-co.talkyard.net"
name = "Forum"

[[params.menu]]

uri = "/docs"

[[params.menu]]

uri = "/about"
