baseURL = "https://datapio.co/"
languageCode = "en-us"
staticDir = ["static"]

title = "Datapio"

[params]

logo = "/img/datapio-logo.png"
description = """
Datapio is an ecosystem of Cloud-Native tools for DevOps, to ease the use and
workflows of Kubernetes.
"""

github = "https://github.com/datapio"
forum = "https://comments-for-datapio-co.talkyard.net"
