name: Deploy Github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
        # with:
        #   submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.60.0'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Configure CNAME
        run: cp ./CNAME ./public/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.WEBSITE_DEPLOY_KEY }}
          EXTERNAL_REPOSITORY: datapio/datapio.github.io
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public

      - name: notify@slack
        uses: Ilshidur/action-slack@master
        env:
          SLACK_USERNAME: CIBot
          SLACK_OVERRIDE_MESSAGE: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          args: "[<https://github.com/datapio/website|website>] Deployment: ${{ job.status }}"
        if: always()
