name: Deploy Github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
        # with:
        #   submodules: true

      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Build index
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: run index

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.72.0'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.WEBSITE_DEPLOY_KEY }}
          external_repository: datapio/datapio.github.io
          publish_branch: master
          publish_dir: ./public
          cname: datapio.co
          allow_empty_commit: true